config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bikes do
    resources :rentals, except: :index
  end
  get "/dashboard", to: 'pages#dashboard', as: 'dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
require 'date'

class Bike < ApplicationRecord
  belongs_to :user
  has_many :rentals, dependent: :destroy
  validates :price, presence: true
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 6 }
  validates :category, presence: true, inclusion: { in: ['Bike', 'Electric Bike', 'Scooter', 'Moto', 'Monocycle'],
                                                    message: "%{ value } is not a valid category." }
  has_one_attached :image
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_description_category,
    against: [ :name, :description, :category ],
    using: {
      tsearch: { prefix: true }
    }

  def availability?(start_date_user, end_date_user)

    user_dates = (start_date_user..end_date_user).map(&:to_s)
    all_booked_dates = rentals.map do |rental|
      rental.rental_dates
    end
    all_booked_dates = all_booked_dates.flatten
    (all_booked_dates & user_dates).length > 0 ? false : true
  end
end

app/models/rental.rb
require 'date'

class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  validates :total_price, presence: true
  validates :user_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  def rental_dates
    return (start_date..end_date).map(&:to_s)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  regex_email = /\A(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})\z/i
  validates :email, uniqueness: { case_sensitive: false }, format: { with: regex_email }, presence: true
  validates :phone_number, uniqueness: { case_sensitive: false }, presence: true
  validates :address, length: { minimum: 5 }, presence: true
  validates :first_name, :last_name, presence: true
  has_many :rentals
  has_many :bikes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :phone_number])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :find_bike, only: [:show, :edit, :update, :destroy]
  def index
    @bikes = policy_scope(Bike).order(created_at: :desc).geocoded
    @bikes = search_query_selection()
    set_marker_image_geocoded() unless @bikes.nil?
  end

  def show
    authorize @bike
  end

  def new
    @bike = Bike.new
    authorize @bike
  end

  def create
    @bike = Bike.new(bike_params)
    authorize @bike
    @bike.user = current_user
    # @bike.address = @bike.user.address
    if @bike.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    authorize @bike
  end

  def update
    @bike.update(bike_params)
    authorize @bike
    redirect_to dashboard_path
  end

  def destroy
    authorize @bike
    @bike.destroy
    redirect_to root_path
  end

  private

  def bike_params
    params.require(:bike).permit(:name, :price, :description, :category, :available, :image)
  end

  def find_bike
    @bike = Bike.find(params[:id])
  end

  def set_marker_image_geocoded
    @markers = @bikes.map do |bike|
        if bike.category == "Bike"
          image = "VehicleBike.png"
        elsif bike.category == 'Electric Bike'
          image = "VehicleElectricBike.png"
        elsif bike.category == 'Moto'
          image = "VehicleMoto.png"
        elsif bike.category == 'Scooter'
          image = "VehicleScooter.png"
        elsif bike.category == 'Monocycle'
          image = "VehicleMonocycle.png"
        end
      {
        lat: bike.latitude,
        lng: bike.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bike: bike }),
        image_url: helpers.asset_url(image)
      }
    end
  end

  def search_query_selection
    # return nil if @rental.start_date < @rental.end_date

    case params.present?
    when params[:query].present? && params[:end_date].present? && params[:start_date].present?
      then @bikes = @bikes.search_by_name_description_category(params[:query]).select {|bike| bike.availability?(params[:start_date], params[:end_date]) }

    when params[:query].present?
      then @bikes = @bikes.search_by_name_description_category(params[:query])

    when params[:end_date].present? && params[:start_date].present?
      then @bikes = @bikes.select {|bike| bike.availability?(params[:start_date], params[:end_date]) }

    when params[:end_date].present? || params[:start_date].present? || params[:query].present?
      then @bikes = nil
    else
      @bikes
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def dashboard
    @user = current_user
    @rentals = @user.rentals
    @bikes = @user.bikes
  end

  def home
    @bikes = policy_scope(Bike).order(created_at: :desc)
  end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  require 'date'
before_action :find_bike, only: [:new, :create, :show, :edit, :update, :destroy]
before_action :find_rental, only: [:edit, :update, :destroy]

  def new
    @rental = Rental.new
    authorize @bike

  end

  def create
    authorize @bike
    @rental = Rental.new(rental_params)
    @user = @bike.user
    @rental.bike = @bike
    @rental.user = current_user
    @rental.total_price = @bike.price * (params["rental"]["end_date"].to_date - params["rental"]["start_date"].to_date).to_i
    if @rental.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def show
    authorize @bike
  end

  def edit
    find_rental
    authorize @bike
  end

  def update
    @rental.update(rental_params)
    authorize @bike
    redirect_to dashboard_path
  end

  def destroy
    @rental.destroy
    redirect_to dashboard_path
  end

  private

  def rental_params
    params.require(:rental).permit(:total_price, :user_id, :bike_id, :start_date, :end_date)
  end

  def find_bike
    @bike = Bike.find(params[:bike_id])
  end

  def find_rental
    @rental = Rental.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_info_window.html.erb
<h2><%= bike.name %></h2>
<p><%= Geocoder.search(bike.address).first.city %></p>
<p><%= bike.price %>€</p>

app/views/bikes/edit.html.erb
<div style="background-color: #8ECAE6; height: 100vh;" class="d-flex align-items-center">
    <div class="row d-flex" style="width: 100%;">
      <div class="container bg-white form-box col-lg-6 col-md-6 col-sm-12" style="padding: 24px;">
        <h2 class="text-center">Edit bike</h2>
        <%= render 'shared/bike_form' %>
      </div>
    </div>
</div>

app/views/bikes/index.html.erb
<div class="container index-grid" style="margin-top: 64px;">
  <div class="row">
    <div class="col-sm-0 col-md-6 col-lg-6" style="margin-top: 64px !important;">
      <h2 class="mb-4"><strong>These bikes are waiting for you</strong></h2>
      <div class="container">
        <% if @bikes.nil? %>
          <%= render 'shared/nil_bike'%>
        <% else %>
          <% @bikes.each do | bike | %>
            <div class="card-bottom">
              <%= render 'shared/bike_card', bike: bike %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-0 col-md-6 col-lg-6">
      <div style="width: 100%; height: 100vh; position: fixed;"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/bikes/new.html.erb
<div style="height: 100vh;" class="d-flex align-items-center pattern-background">
    <div class="row d-flex" style="width: 100%;">
      <div class="container bg-white form-box col-lg-6 col-md-6 col-sm-12" style="padding: 24px;">
        <h2 class="text-center">Add a bike</h2>
        <%= render 'shared/bike_form' %>
      </div>
    </div>
</div>
<!-->

app/views/bikes/show.html.erb
<div style="height: 100vh;" class="d-flex align-items-center pattern-background">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="row justify-content-center">
      <p style="margin-top: 100px;" class="col-sm-12 col-md-8 col-lg-8">
        <i class="fas fa-arrow-left icon-back"></i>
        <%= link_to 'Back', :back, class:"back-link" %>
      </p>
      </div>
      <div class="col-sm-12 col-md-8 col-lg-8 bg-white p-3" style="border-radius: 24px;">
        <div class="row">
          <div class="col-sm-12 col-md-6 col-lg-6 img-card">
            <%= cl_image_tag(@bike.image.key,
            width: 400, height: 400, crop: :fill) %>
          </div>
          <div class="col-sm-12 col-md-6 col-lg-6 row">
            <h2><%= @bike.name %></h2>
            <p>
            <% if @bike.category == "Bike" %>
              <i class="fas fa-bicycle icon-category"></i><%= @bike.category %>
            <% end %>
            <% if @bike.category == "Scooter" %>
              <i class="fas fa-charging-station icon-category"></i><%= @bike.category %>
            <% end %>
            <% if @bike.category == "Electric Bike" %>
              <i class="fas fa-bicycle icon-category"></i><%= @bike.category %>
            <% end %>
            <% if @bike.category == "Moto" %>
              <i class="fas fa-tachometer-alt icon-category"></i><%= @bike.category %>
            <% end %>
            <% if @bike.category == "Monocycle" %>
              <i class="fas fa-dharmachakra icon-category"></i><%= @bike.category %>
            <% end %>
            </p>
            <div class="details-card-owner mt-3 mb-3">
            <%= image_tag "profile_picture_card.png", class: "avatar" %>
            <p><%= @bike.user.first_name %></p>
            </div>
            <div class="empty-card-small">
              <p>
                <span class="quote"><i class="fas fa-quote-left"></i></span>
                <%= @bike.description %>
                <span class="quote"><i class="fas fa-quote-right"></i></span>
              </p>
            </div>
            <div class="d-flex justify-content-start">
              <div class="card-action m-2">
                <% if policy(@bike).destroy? %>
                <i class="far fa-trash-alt delete-link mt-3"></i>
                <%=  link_to "Delete",
                        bike_path(@bike),
                        method: :delete,
                        data: { confirm: "Do you want to delete this bike?" }, class:"delete-link ml-2"%>
                <% end %>
              </div>
              <div class="card-action m-2">
                <% if policy(@bike).destroy? %>
                <i class="far fa-edit delete-link mt-3"></i>
                <%=  link_to "Edit",
                        edit_bike_path(@bike), class:"delete-link ml-2"%>
                <% end %>
              </div>
            </div>
            <% unless current_user == @bike.user %>
              <%= link_to 'Make a rental', new_bike_rental_path(@bike, start_date: params[:start_date], end_date: params[:end_date]), class:"primary-button text-center m-2", style:"padding: 16px 24px;" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikeLord2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class= "<%= "home" if params[:action] == "home" %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container bg-white" style="margin-top: 72px;">
  <div class="row">
    <h1 class="section-heading">My Rentals</h1>
    <div>
      <% if @rentals.any? %>
        <div class="container bike-grid">
          <% @rentals.each do |rental| %>
          <%= render 'shared/bike_card', bike: rental.bike %>
            <% if policy(rental.bike).edit? %>

            <% end %>
          <% end %>
        </div>
      <% else %>
        <div class="empty-card col-md-8 col-sm-12 d-flex align-items-center">
          <div>
            <i class="far fa-hand-peace picto mr-3"></i>
          </div>
          <div>
            <h2>You don't have any rental yet !</h2>
            <p>Feel freedom and smoothness during your journeys. Make a rental to begin your adventure!</p>
            <button class="btn primary-button">
              <%= link_to "Rent a bike" %>
            </button>
          </div>
        <div>
      <% end %>
    </div>

  </div>
  <div class="row">
    <h1 class="section-heading">My Bikes</h1>
    <div>
      <% if @bikes.any? %>
      <div class="container bike-grid">
        <% @bikes.each do |bike| %>
        <%= render 'shared/bike_card', bike: bike %>
          <% if policy(bike).edit? %>

          <% end %>
        <% end %>
      </div>
      <% else %>
        <div class="empty-card col-md-8 col-sm-12 d-flex align-items-center">
          <div>
            <i class="fas fa-bicycle picto"></i>
          </div>
          <div>
            <h2>You don't own any bike (yet) !</h2>
            <p>Become an owner adding a bike. Make easy money and good friends when lending your bike!</p>
            <button class="btn secondary-button">
              <%= link_to "Add a bike", new_bike_path %>
            </button>
          </div>
        <div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.1)), url('https://imagizer.imageshack.com/img924/767/uAGSJg.png')">
  <div class="container">
    <%= image_tag("logo_big.png", crop: :fill, class:"mb-3") %>
    <h1><span>Get a bike</span> and <span>ride</span> till' you <span>die</span>!</h1>
    <div class="">
      <div class="col-sm-12 col-md-6 row">
      <%= form_tag bikes_path, method: :get do %>
      <div class="row">
        <div class="col-12">
          <%= text_field_tag :query,
          params[:query],
          class: "form-control mt-4",
          placeholder: "Find a bike"
          %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-8 col-md-4">
          <%= date_field_tag :start_date,
          params[:start_date],
          class: "form-control mt-4",
          # data: controller_name => flat picker
          placeholder: "Start date"
          %>
        </div>
        <div class="col-sm-8 col-md-4">
          <%= date_field_tag :end_date,
          params[:end_date],
          class: "form-control mt-4",
          placeholder: "End date"
          %>
        </div>
        <div class="col-sm-8 col-md-4">
        <%= submit_tag "Browse our bikes!", class: "primary-button mt-4" %>
          <% end %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <h1 style="margin-top: 72px;">Latest bikes on the streets!</h1>
  <div class="row d-flex">
    <% @bikes.first(4).each do | bike | %>
      <div class="col-sm-12 col-md-3 col-lg-3 p-2">
        <%= render 'shared/bike_card_small', bike: bike %>
      </div>
    <% end %>
  </div>
</div>
<div class="container" style="margin-top: 72px">
  <h2>Discover the bikes of the community!</h2>
  <div class="row mt-3">
    <% @bikes.first(4).each do | bike | %>
      <div class="col-sm-12 col-md-6 col-lg-6 p-2">
        <%= render 'shared/bike_card', bike: bike %>
      </div>
    <% end %>
  </div>
</div>


<%# <i class="fa-duotone fa-magnifying-glass"></i> %>
<%# placeholder dans date
<%# display des dates %>
<%# effet fondu navbar %>

app/views/rentals/edit.html.erb
<br>
<br>
<br>

<h1>Did you change your mind ? We got you! You can edit the duration of your booking
</h1>
<%= simple_form_for [@bike, @rental] do |f| %>
  <%= f.input :start_date, label:"Rental start date" %>
  <%= f.input :end_date, label:"Rental end date"  %>
  <%= f.button :submit, class:"primary-button mt-2" %>
<% end %>

app/views/rentals/new.html.erb
<div style="height: 100vh;" class="d-flex align-items-center pattern-background">
<div class="container bg-white" style="border-radius: 24px">
<h1 class="section-heading" id="margin-title">Rent this bike</h1>
<div class="container d-flex">
  <div class="row">
    <div class="col-md-6">
      <h4 class="my-4">You want to rent this bike from <em><%= Date.parse(params[:start_date]) %></em> to <em><%= Date.parse(params[:end_date]) %></em></h4>
      <%= render 'shared/bike_card', bike: @bike %>
        <h3 class="my-4"> Total price : <%= @bike.price * (Date.parse(params[:end_date]) - Date.parse(params[:start_date])).to_i %> €</h3>
    </div>
    <div class="col-md-6 empty-card p-5">
      <h3 class="my-4">Wanna ride a bit more ? You can always change your dates</h3>
      <%= render 'shared/create_rental_form.html' %>
    </div>
  </div>
</div>
</div>
</div>

app/views/shared/_bike_card.html.erb
<div class="bike-card">
<%= link_to bike_path(bike, start_date: params[:start_date], end_date: params[:end_date]), class:"text-decoration-none" do %>

  <div class="img-card">
   <%= cl_image_tag(bike.image.key,
      width: 150, height: 150, crop: :fill) %>
  </div>

  <div class="details-card">
    <div class="details-card-bike">
      <h3><b><%= bike.name.first(25) %></b></h3>

      <p>
      <% if bike.category == "Bike" %>
        <i class="fas fa-bicycle icon-category"></i><%= bike.category %>
      <% end %>
      <% if bike.category == "Scooter" %>
        <i class="fas fa-tachometer-alt icon-category"></i><%= bike.category %>
      <% end %>
      <% if bike.category == "Electric Bike" %>
        <i class="fas fa-charging-station icon-category"></i><%= bike.category %>
      <% end %>
      <% if bike.category == "Moto" %>
        <i class="fas fa-motorcycle icon-category"></i><%= bike.category %>
      <% end %>
      <% if bike.category == "Monocycle" %>
        <i class="fas fa-dharmachakra icon-category"></i><%= bike.category %>
      <% end %>
      </p>
    </div>

    <div class="details-card-owner">
      <%= image_tag "profile_picture_card.png", class: "avatar" %>
      <p><%= bike.user.first_name %></p>
    </div>
    <% end %>
  </div>
  <div class="settings-card">
    <h2><%= bike.price %>€<span id="per-day">/day</span></h2>
    <div class="icons-card">
    <% if policy(bike).edit? %>
        <%= link_to edit_bike_path(bike) do %>
          <i class="far fa-edit delete-link"></i>
        <% end %>
    <% end %>
      <% if policy(bike).destroy? %>
        <%= link_to dashboard_path,
            method: :delete,
            data: { confirm: "Do you want to delete this bike?" },
            class:"delete-link ml-2" do %>
            <i class="far fa-trash-alt delete-link"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_bike_card_small.erb
<div class="bike-card-small d-flex flex-column">
  <%= link_to bike_path(bike), class:"text-decoration-none" do %>
    <div class="row">
        <div class="img-card text-center">
        <%= cl_image_tag(bike.image.key, crop: :fill, :class => "show-img-width") %>
        </div>
    </div>

      <div class="details-card-bike">
        <div class="row d-flex justify-content-between mt-3">
          <div class="col-8">
            <h4><b><%= bike.name.first(25) %></b></h4>
          </div>
          <div class="col-4" style="position: relative; right: 24px;">
            <h3><%= bike.price %>€<span id="per-day">/day</span></h3>
          </dic>
        </div>
        <p>
        <% if bike.category == "Bike" %>
          <i class="fas fa-bicycle icon-category"></i><%= bike.category %>
        <% end %>
        <% if bike.category == "Scooter" %>
          <i class="fas fa-tachometer-alt icon-category"></i><%= bike.category %>
        <% end %>
        <% if bike.category == "Electric Bike" %>
          <i class="fas fa-charging-station icon-category"></i><%= bike.category %>
        <% end %>
        <% if bike.category == "Moto" %>
          <i class="fas fa-motorcycle icon-category"></i><%= bike.category %>
        <% end %>
        <% if bike.category == "Monocycle" %>
          <i class="fas fa-dharmachakra icon-category"></i><%= bike.category %>
        <% end %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_bike_form.html.erb
<%= simple_form_for @bike do |f| %>
  <%= f.input :name, label:"Bike name", class:"field" %>
  <%= f.input :category, :collection => ['Bike', 'Electric Bike', 'Scooter', 'Moto', 'Monocycle'], as: :select %>
  <%= f.input :price %>
  <%= f.input :image, as: :file %>
  <%= f.input :description, as: :text  %>
  <%= f.button :submit, class:"primary-button mt-2" %>
<% end %>

app/views/shared/_create_rental_form.html.erb
<%= simple_form_for [@bike, @rental] do |f| %>
  <%= f.date_field :start_date, label:"Start date", value: Date.parse(params[:start_date]) %>
  <%= f.date_field :end_date, label:"End date", value: Date.parse(params[:end_date]) %>
  <%= f.button :submit, class:"primary-button mt-4", value: "Confirm rental" %>
<% end %>

app/views/shared/_edit_rental_form.html.erb
<%= simple_form_for [@bike, @rental] do |f| %>
  <%= f.input :start_date, label:"Start Date" %>
  <%= f.input :end_date, label: "End Date" %>
  <%= f.button :submit, class:"primary-button mt-2" %>
<% end %>

app/views/shared/_flashes.html.erb
<!-- app/views/layouts/application.html.erb -->
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top d-flex">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("logo_bike_white.png") %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav d-flex align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add a bike', new_bike_path, class:"secondary-button mt-4" %>
          </li>
          <li class="nav-item" id="dashboard-entry">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "nav_bar_profile.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item navbar-lewagon-menu", id:"logout" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link navbar-lewagon" do %>
                <i class="far fa-user-circle mr-2 icon-login"></i>
                <strong>Login</strong>
              <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_nil_bike.html.erb
<p>You made a selection error</p>

app/views/shared/_payment_form.html.erb
  <div class="container bg-white form-box">
    <form action="/dashboard">
      <div class="row">
        <label for="fname" class="form-label string required"> Full Name</label>
        <input class="form-control string required" type="text" id="fname" name="firstname" placeholder="John M. Doe">
      </div>
      <div class="row">
        <label for="ccnum" class="form-label string required">Credit card number</label>
      </div>
      <div class="row">
        <input class="form-control string required" type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
      </div>
      <div class="row">
        <label for="expmonth" class="form-label string required col-12">Expiration date</label>
      </div>
      <div class="row">
        <input class="form-control string required col" type="text" id="expmonth" name="expmonth" placeholder="September">
        <input class="form-control string required col" type="text" id="expyear" name="expyear" placeholder="2018">
      </div>
      <div class="row">
      <input type="submit" value="Checkout" class="btn primary-button mt-3">
      </div>
    </form>
  </div>